package android

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/backsofangels/grimoire/internal/providers"
	"github.com/backsofangels/grimoire/internal/validator"
)

// Add creates a single resource (activity, fragment, viewmodel) inside an
// existing Android module. Expects keys in cfg:
// - Kind: "activity" | "fragment" | "viewmodel"
// - Name: class name (e.g. MyActivity)
// - PackageName: java package (optional; will try to detect)
// - Lang: "kotlin" | "java" (defaults to kotlin)
// - Module: module name (defaults to "app")
// - Layout: layout resource name (optional; autogenerated if empty)
// - Override: bool (overwrite existing files)
func (a *AndroidProvider) Add(cfg providers.ProviderConfig) error {
	kind := strings.ToLower(getString(cfg, "Kind", "kind"))
	name := getString(cfg, "Name", "name")
	if name == "" {
		return fmt.Errorf("resource Name is required")
	}
	if err := validateClassName(name); err != nil {
		return err
	}

	lang := strings.ToLower(getString(cfg, "Lang", "lang"))
	if lang == "" {
		lang = "kotlin"
	}

	module := getString(cfg, "Module", "module")
	if module == "" {
		module = "app"
	}

	pkg := getString(cfg, "PackageName", "package")
	if pkg == "" {
		// try to detect from AndroidManifest
		man := filepath.Join(module, "src", "main", "AndroidManifest.xml")
		if b, err := os.ReadFile(man); err == nil {
			s := string(b)
			if idx := strings.Index(s, "package=\""); idx != -1 {
				start := idx + len("package=\"")
				if end := strings.Index(s[start:], "\""); end != -1 {
					pkg = s[start : start+end]
				}
			}
		}
		if pkg == "" {
			return fmt.Errorf("package name not provided and could not be detected; use --package")
		}
	}

	layout := getString(cfg, "Layout", "layout")
	if layout == "" {
		base := toSnake(name)
		switch kind {
		case "activity":
			layout = "activity_" + base
		case "fragment":
			layout = "fragment_" + base
		default:
			layout = strings.ToLower(base)
		}
	}

	override := false
	if v, ok := cfg["Override"].(bool); ok && v {
		override = true
	}
	if v, ok := cfg["override"].(bool); ok && v {
		override = true
	}

	pkgPath := validator.PackageToPath(pkg)
	srcDir := filepath.Join(module, "src", "main", "java", pkgPath)
	if err := os.MkdirAll(srcDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", srcDir, err)
	}

	// Determine source filename and template
	var tmplName string
	var outFile string
	switch lang {
	case "kotlin":
		outFile = filepath.Join(srcDir, name+".kt")
		switch kind {
		case "activity":
			tmplName = "activity.kt.tmpl"
		case "fragment":
			tmplName = "fragment.kt.tmpl"
		case "viewmodel":
			tmplName = "viewmodel.kt.tmpl"
		default:
			return fmt.Errorf("unsupported kind: %s", kind)
		}
	case "java":
		outFile = filepath.Join(srcDir, name+".java")
		switch kind {
		case "activity":
			tmplName = "activity.java.tmpl"
		case "fragment":
			tmplName = "fragment.java.tmpl"
		case "viewmodel":
			tmplName = "viewmodel.java.tmpl"
		default:
			return fmt.Errorf("unsupported kind: %s", kind)
		}
	default:
		return fmt.Errorf("unsupported language: %s", lang)
	}

	if _, err := os.Stat(outFile); err == nil && !override {
		return fmt.Errorf("target file already exists: %s", outFile)
	}

	data := map[string]any{
		"PackageName": pkg,
		"ClassName":   name,
		"LayoutName":  layout,
		"Title":       name,
	}

	// render source
	src, err := renderTemplate(tmplName, data)
	if err != nil {
		return err
	}
	if err := writeFile(outFile, src); err != nil {
		return err
	}

	// render layout for activities/fragments (only XML templates for now)
	if kind == "activity" || kind == "fragment" {
		layoutDir := filepath.Join(module, "src", "main", "res", "layout")
		if err := os.MkdirAll(layoutDir, 0o755); err != nil {
			return err
		}
		var layoutTmpl string
		if kind == "activity" {
			layoutTmpl = "layout_activity.xml.tmpl"
		} else {
			layoutTmpl = "layout_fragment.xml.tmpl"
		}
		layoutPath := filepath.Join(layoutDir, layout+".xml")
		if _, err := os.Stat(layoutPath); err == nil && !override {
			// skip if exists
		} else {
			lsrc, err := renderTemplate(layoutTmpl, data)
			if err != nil {
				return err
			}
			if err := writeFile(layoutPath, lsrc); err != nil {
				return err
			}
		}
	}

	// If user requested an associated ViewModel, generate it alongside the
	// activity/fragment (unless the kind itself is viewmodel).
	includeVM := false
	if v, ok := cfg["ViewModel"].(bool); ok && v {
		includeVM = true
	}
	if !includeVM {
		if v, ok := cfg["viewmodel"].(bool); ok && v {
			includeVM = true
		}
	}
	if includeVM && kind != "viewmodel" {
		vmName := name + "ViewModel"
		if err := validateClassName(vmName); err != nil {
			return err
		}
		var vmTmpl string
		var vmOut string
		if lang == "kotlin" {
			vmOut = filepath.Join(srcDir, vmName+".kt")
			vmTmpl = "viewmodel.kt.tmpl"
		} else {
			vmOut = filepath.Join(srcDir, vmName+".java")
			vmTmpl = "viewmodel.java.tmpl"
		}
		if _, err := os.Stat(vmOut); err == nil && !override {
			// skip
		} else {
			vdata := map[string]any{
				"PackageName": pkg,
				"ClassName":   vmName,
			}
			vsrc, err := renderTemplate(vmTmpl, vdata)
			if err != nil {
				return err
			}
			// Apply DI-specific modifications to the ViewModel source
			di := strings.ToLower(getString(cfg, "DI", "di"))
			if di == "hilt" {
				if strings.ToLower(lang) == "kotlin" {
					vsrc = modifyViewModelForHilt(vsrc, vmName)
				} else if strings.ToLower(lang) == "java" {
					vsrc = modifyViewModelForHiltJava(vsrc, vmName)
				}
			}
			if err := writeFile(vmOut, vsrc); err != nil {
				return err
			}
		}
	}

	// Dependency injection wiring (Hilt / Koin)
	di := strings.ToLower(getString(cfg, "DI", "di"))
	if di == "" {
		if v, ok := cfg["DI"].(string); ok {
			di = strings.ToLower(v)
		}
		if di == "" {
			if v, ok := cfg["di"].(string); ok {
				di = strings.ToLower(v)
			}
		}
	}
	if di == "hilt" {
		if err := ensureHiltSetup(module, pkg, lang); err != nil {
			return err
		}
		// Add @AndroidEntryPoint to generated component
		if lang == "kotlin" && (kind == "activity" || kind == "fragment") {
			if b, err := os.ReadFile(outFile); err == nil {
				ns := addAndroidEntryPointKotlin(string(b), name)
				if ns != string(b) {
					_ = os.WriteFile(outFile, []byte(ns), 0o644)
				}
			}
		}
		if lang == "java" && (kind == "activity" || kind == "fragment") {
			if b, err := os.ReadFile(outFile); err == nil {
				ns := addAndroidEntryPointJava(string(b), name)
				if ns != string(b) {
					_ = os.WriteFile(outFile, []byte(ns), 0o644)
				}
			}
		}
		// If the resource itself is a ViewModel, apply Hilt modifications to it
		if kind == "viewmodel" {
			if strings.ToLower(lang) == "kotlin" {
				if b, err := os.ReadFile(outFile); err == nil {
					ns := modifyViewModelForHilt(string(b), name)
					if ns != string(b) {
						_ = os.WriteFile(outFile, []byte(ns), 0o644)
					}
				}
			} else if strings.ToLower(lang) == "java" {
				if b, err := os.ReadFile(outFile); err == nil {
					ns := modifyViewModelForHiltJava(string(b), name)
					if ns != string(b) {
						_ = os.WriteFile(outFile, []byte(ns), 0o644)
					}
				}
			}
		}
	} else if di == "koin" {
		if err := ensureKoinSetup(module, pkg, lang); err != nil {
			return err
		}
	}

	// Navigation wiring: add a nav_graph entry for fragments (or activities if requested)
	navAdd := false
	if v, ok := cfg["Nav"].(bool); ok && v {
		navAdd = true
	}
	if !navAdd {
		if v, ok := cfg["nav"].(bool); ok && v {
			navAdd = true
		}
	}
	if navAdd {
		if err := ensureNavEntry(module, pkg, name, kind); err != nil {
			return err
		}
	}

	return nil
}

// getString looks up multiple possible keys in cfg and returns first non-empty
func getString(cfg providers.ProviderConfig, keys ...string) string {
	for _, k := range keys {
		if v, ok := cfg[k].(string); ok && v != "" {
			return v
		}
	}
	return ""
}

func validateClassName(n string) error {
	if n == "" {
		return fmt.Errorf("empty class name")
	}
	r := []rune(n)
	if len(r) == 0 {
		return fmt.Errorf("invalid class name")
	}
	if r[0] >= '0' && r[0] <= '9' {
		return fmt.Errorf("class name cannot start with a digit")
	}
	// simple char whitelist: letters, digits and _
	for _, ch := range r {
		if !(ch == '_' || (ch >= '0' && ch <= '9') || (ch >= 'A' && ch <= 'Z') || (ch >= 'a' && ch <= 'z')) {
			return fmt.Errorf("invalid character '%c' in class name", ch)
		}
	}
	return nil
}

// toSnake converts CamelCase to snake_case (basic implementation)
func toSnake(s string) string {
	var parts []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			parts = append(parts, '_')
		}
		parts = append(parts, r)
	}
	return strings.ToLower(string(parts))
}

// addAndroidEntryPointKotlin injects the Hilt @AndroidEntryPoint import and
// annotation into a small Kotlin source string.
func addAndroidEntryPointKotlin(src, className string) string {
	if strings.Contains(src, "@AndroidEntryPoint") {
		return src
	}
	imp := "import dagger.hilt.android.AndroidEntryPoint\n"
	if !strings.Contains(src, imp) {
		// insert import after package line
		if idx := strings.Index(src, "\n"); idx != -1 {
			src = src[:idx+1] + imp + src[idx+1:]
		} else {
			src = imp + "\n" + src
		}
	}
	// annotate class declaration
	cls := "class " + className
	if p := strings.Index(src, cls); p != -1 {
		src = src[:p] + "@AndroidEntryPoint\n" + src[p:]
	} else if p := strings.Index(src, "class "); p != -1 {
		src = src[:p] + "@AndroidEntryPoint\n" + src[p:]
	}
	return src
}

// addAndroidEntryPointJava injects the Hilt import and annotation into Java
// source.
func addAndroidEntryPointJava(src, className string) string {
	if strings.Contains(src, "@AndroidEntryPoint") {
		return src
	}
	imp := "import dagger.hilt.android.AndroidEntryPoint;\n"
	if !strings.Contains(src, imp) {
		if idx := strings.Index(src, "\n"); idx != -1 {
			src = src[:idx+1] + imp + src[idx+1:]
		} else {
			src = imp + "\n" + src
		}
	}
	// annotate before class
	cls := "class " + className
	if p := strings.Index(src, cls); p != -1 {
		src = src[:p] + "@AndroidEntryPoint\n" + src[p:]
	} else if p := strings.Index(src, "class "); p != -1 {
		src = src[:p] + "@AndroidEntryPoint\n" + src[p:]
	}
	return src
}

// modifyViewModelForHilt rewrites a simple ViewModel source to include
// @HiltViewModel and constructor @Inject for Kotlin.
func modifyViewModelForHilt(src, className string) string {
	if strings.Contains(src, "@HiltViewModel") {
		return src
	}
	imp := "import dagger.hilt.android.lifecycle.HiltViewModel\nimport javax.inject.Inject\n"
	if !strings.Contains(src, "HiltViewModel") {
		if idx := strings.Index(src, "\n"); idx != -1 {
			src = src[:idx+1] + imp + src[idx+1:]
		} else {
			src = imp + "\n" + src
		}
	}
	// replace simple class declaration
	// class Foo : ViewModel() { -> @HiltViewModel\nclass Foo @Inject constructor() : ViewModel() {
	old := "class " + className + " : ViewModel()"
	if strings.Contains(src, old) {
		src = strings.Replace(src, old, "@HiltViewModel\nclass "+className+" @Inject constructor() : ViewModel()", 1)
	}
	return src
}

// modifyViewModelForHiltJava injects Hilt annotations and an @Inject
// constructor into a simple Java ViewModel source string.
func modifyViewModelForHiltJava(src, className string) string {
	if strings.Contains(src, "@HiltViewModel") || strings.Contains(src, "HiltViewModel") {
		// already modified
		if strings.Contains(src, "@Inject") {
			return src
		}
	}
	imp := "import dagger.hilt.android.lifecycle.HiltViewModel;\nimport javax.inject.Inject;\n"
	if !strings.Contains(src, "HiltViewModel") {
		if idx := strings.Index(src, "\n"); idx != -1 {
			src = src[:idx+1] + imp + src[idx+1:]
		} else {
			src = imp + "\n" + src
		}
	}
	// annotate before class
	cls := "public class " + className
	if p := strings.Index(src, cls); p != -1 {
		src = src[:p] + "@HiltViewModel\n" + src[p:]
	} else if p := strings.Index(src, "class "); p != -1 {
		src = src[:p] + "@HiltViewModel\n" + src[p:]
	}
	// add a simple @Inject constructor if none exists
	if !strings.Contains(src, "@Inject") {
		// find first opening brace after class declaration
		if idx := strings.Index(src, "{"); idx != -1 {
			insertAt := idx + 1
			ctor := fmt.Sprintf("\n    @Inject\n    public %s() {}\n", className)
			src = src[:insertAt] + ctor + src[insertAt:]
		}
	}
	return src
}

// ensureHiltSetup updates root and module build files, creates Application
// annotated with @HiltAndroidApp, and updates the AndroidManifest.
func ensureHiltSetup(module, pkg, lang string) error {
	// add classpath to root build.gradle if missing
	root := "build.gradle"
	if b, err := os.ReadFile(root); err == nil {
		s := string(b)
		if !strings.Contains(s, "hilt-android-gradle-plugin") {
			// try to find the dependencies block under buildscript
			if idx := strings.Index(s, "dependencies {"); idx != -1 {
				// insert classpath after the dependencies { line
				if nl := strings.Index(s[idx:], "\n"); nl != -1 {
					insertAt := idx + nl + 1
					add := "        classpath \"com.google.dagger:hilt-android-gradle-plugin:2.46.1\"\n"
					s = s[:insertAt] + add + s[insertAt:]
					_ = os.WriteFile(root, []byte(s), 0o644)
				}
			}
		}
	}

	// modify module build.gradle (Groovy) if present
	mod := filepath.Join(module, "build.gradle")
	if b, err := os.ReadFile(mod); err == nil {
		s := string(b)
		// plugins block: add dagger.hilt.android.plugin
		if !strings.Contains(s, "dagger.hilt.android.plugin") {
			if p := strings.Index(s, "plugins {"); p != -1 {
				if e := strings.Index(s[p:], "}"); e != -1 {
					insertAt := p + e
					add := "\n    id 'dagger.hilt.android.plugin'\n"
					s = s[:insertAt] + add + s[insertAt:]
				}
			} else {
				// apply plugin fallback
				s = "apply plugin: 'dagger.hilt.android.plugin'\n" + s
			}
		}
		// add kotlin-kapt plugin for Kotlin projects
		if strings.ToLower(lang) == "kotlin" && !strings.Contains(s, "kotlin-kapt") {
			if p := strings.Index(s, "plugins {"); p != -1 {
				if e := strings.Index(s[p:], "}"); e != -1 {
					insertAt := p + e
					add := "\n    id 'kotlin-kapt'\n"
					s = s[:insertAt] + add + s[insertAt:]
				}
			} else {
				s = "apply plugin: 'kotlin-kapt'\n" + s
			}
		}
		// append Hilt dependencies in a new dependencies block if missing
		if !strings.Contains(s, "com.google.dagger:hilt-android") {
			addDeps := "\n// Hilt dependencies added by grimoire\ndependencies {\n    implementation 'com.google.dagger:hilt-android:2.46.1'\n    kapt 'com.google.dagger:hilt-android-compiler:2.46.1'\n}\n"
			s = s + addDeps
		}
		_ = os.WriteFile(mod, []byte(s), 0o644)
	}

	// create Application class
	appDir := filepath.Join(module, "src", "main", "java", validator.PackageToPath(pkg))
	_ = os.MkdirAll(appDir, 0o755)
	appFile := filepath.Join(appDir, "MyApplication.kt")
	if _, err := os.Stat(appFile); err != nil {
		tmpl := fmt.Sprintf("package %s\n\nimport android.app.Application\nimport dagger.hilt.android.HiltAndroidApp\n\n@HiltAndroidApp\nclass MyApplication : Application() {}\n", pkg)
		_ = os.WriteFile(appFile, []byte(tmpl), 0o644)
	}

	// update AndroidManifest to reference application name
	man := filepath.Join(module, "src", "main", "AndroidManifest.xml")
	if b, err := os.ReadFile(man); err == nil {
		s := string(b)
		if !strings.Contains(s, "android:name=") {
			if ap := strings.Index(s, "<application"); ap != -1 {
				if gt := strings.Index(s[ap:], ">"); gt != -1 {
					insertAt := ap + gt
					s = s[:insertAt] + " android:name=\".MyApplication\"" + s[insertAt:]
					_ = os.WriteFile(man, []byte(s), 0o644)
				}
			}
		}
	}

	return nil
}

// ensureKoinSetup creates a minimal Koin Application and adds dependencies.
func ensureKoinSetup(module, pkg, lang string) error {
	// modify module build.gradle to include Koin
	mod := filepath.Join(module, "build.gradle")
	if b, err := os.ReadFile(mod); err == nil {
		s := string(b)
		if !strings.Contains(s, "io.insert-koin:koin-android") {
			addDeps := "\n// Koin dependencies added by grimoire\ndependencies {\n    implementation 'io.insert-koin:koin-android:3.4.0'\n}\n"
			s = s + addDeps
			_ = os.WriteFile(mod, []byte(s), 0o644)
		}
	}

	// create Application class starter for Koin
	appDir := filepath.Join(module, "src", "main", "java", validator.PackageToPath(pkg))
	_ = os.MkdirAll(appDir, 0o755)
	appFile := filepath.Join(appDir, "MyApplication.kt")
	if _, err := os.Stat(appFile); err != nil {
		tmpl := fmt.Sprintf("package %s\n\nimport android.app.Application\nimport org.koin.core.context.startKoin\nimport org.koin.android.ext.koin.androidContext\n\nclass MyApplication : Application() {\n    override fun onCreate() {\n        super.onCreate()\n        startKoin {\n            androidContext(this@MyApplication)\n            // modules(...)\n        }\n    }\n}\n", pkg)
		_ = os.WriteFile(appFile, []byte(tmpl), 0o644)
	}

	return nil
}

// ensureNavEntry creates or updates a navigation graph with an entry for the
// newly created fragment/activity.
func ensureNavEntry(module, pkg, className, kind string) error {
	navDir := filepath.Join(module, "src", "main", "res", "navigation")
	_ = os.MkdirAll(navDir, 0o755)
	navFile := filepath.Join(navDir, "nav_graph.xml")
	id := toSnake(className)
	fragmentNode := fmt.Sprintf("    <fragment android:id=\"@+id/%s\" android:name=\"%s.%s\" android:label=\"%s\" />\n", id, pkg, className, className)

	if b, err := os.ReadFile(navFile); err == nil {
		s := string(b)
		if strings.Contains(s, fmt.Sprintf("android:name=\"%s.%s\"", pkg, className)) {
			return nil // already present
		}
		// insert before closing </navigation>
		if idx := strings.LastIndex(s, "</navigation>"); idx != -1 {
			s = s[:idx] + fragmentNode + s[idx:]
			_ = os.WriteFile(navFile, []byte(s), 0o644)
			// ensure nav dependencies in module
			_ = ensureNavDependencies(module)
			return nil
		}
	}

	// create new nav_graph.xml
	content := fmt.Sprintf("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<navigation xmlns:android=\"http://schemas.android.com/apk/res/android\" xmlns:app=\"http://schemas.android.com/apk/res-auto\" android:id=\"@+id/nav_graph\" app:startDestination=\"@id/%s\">\n", id)
	content += fragmentNode
	content += "</navigation>\n"
	_ = os.WriteFile(navFile, []byte(content), 0o644)
	_ = ensureNavDependencies(module)
	return nil
}

func ensureNavDependencies(module string) error {
	mod := filepath.Join(module, "build.gradle")
	if b, err := os.ReadFile(mod); err == nil {
		s := string(b)
		if !strings.Contains(s, "androidx.navigation:navigation-fragment-ktx") {
			addDeps := "\n// Navigation dependencies added by grimoire\ndependencies {\n    implementation 'androidx.navigation:navigation-fragment-ktx:2.6.0'\n    implementation 'androidx.navigation:navigation-ui-ktx:2.6.0'\n}\n"
			s = s + addDeps
			_ = os.WriteFile(mod, []byte(s), 0o644)
		}
	}
	return nil
}
