package android

import (
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/backsofangels/grimoire/internal/common"
	"github.com/backsofangels/grimoire/internal/providers"
	"github.com/backsofangels/grimoire/internal/validator"
)

func renderTemplate(name string, data any) (string, error) {
	path := filepath.ToSlash(filepath.Join("templates", name))
	content, err := fs.ReadFile(templateFS, path)
	if err != nil {
		return "", fmt.Errorf("read template %s: %w", name, err)
	}
	return common.RenderTemplate(name, string(content), data)
}

func writeFile(path string, content string) error {
	return common.WriteFile(path, content)
}

func initGit(dir string) error {
	// Non-fatal if git init fails
	return common.InitGit(dir)
}

// checkJavaAvailable runs `java -version` to ensure Java is installed and on PATH.
// Returns a user-friendly error with install hints if Java is missing.
func checkJavaAvailable() error {
	if _, err := exec.LookPath("java"); err != nil {
		guide := `Java not found in PATH.
Grimoire requires Java (JDK or JRE) to run Gradle and build Android projects.

Quick install hints:
- Windows (Scoop): scoop install temurin
- Windows (Chocolatey): choco install temurin
- macOS (Homebrew): brew install temurin
- Linux (SDKMAN): curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java
- Debian/Ubuntu (apt): sudo apt-get install default-jdk

After installing, ensure 'java' is on your PATH and re-run ` + "`grimoire new`" + `.
`
		return fmt.Errorf(guide)
	}

	cmd := exec.Command("java", "-version")
	cmd.Env = os.Environ()
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("java -version failed: %w", err)
	} else {
		_ = out
	}
	return nil
}

// ensureGradleWrapper generates or downloads a Gradle wrapper into outputDir.
// Strategy:
// 1) If `gradle` CLI is available, run `gradle wrapper --gradle-version <ver>` in a temp dir and copy results.
// 2) Otherwise download the Gradle distribution zip and assemble the wrapper jar from it.
func ensureGradleWrapper(outputDir, gradleVersion string) error {
	// Verify Java is available before invoking Gradle.
	if err := checkJavaAvailable(); err != nil {
		return err
	}
	// Use system `gradle` to generate the wrapper. If it's not available, return
	// a helpful error directing the user to install Gradle for their OS.
	if p, err := exec.LookPath("gradle"); err == nil && p != "" {
		tmp, err := os.MkdirTemp("", "gradle-wrapper-gen-*")
		if err != nil {
			return fmt.Errorf("mktemp: %w", err)
		}
		defer os.RemoveAll(tmp)

		// Create minimal Gradle build files so `gradle wrapper` can run in a
		// fresh temp directory. Gradle requires at least a settings or build
		// file to consider the directory a build root.
		settings := "rootProject.name = 'grimoire-wrapper-temp'\n"
		if err := os.WriteFile(filepath.Join(tmp, "settings.gradle"), []byte(settings), 0o644); err != nil {
			return fmt.Errorf("write temp settings.gradle: %w", err)
		}
		build := "// minimal build file generated by grimoire\n"
		if err := os.WriteFile(filepath.Join(tmp, "build.gradle"), []byte(build), 0o644); err != nil {
			return fmt.Errorf("write temp build.gradle: %w", err)
		}

		cmd := exec.Command(p, "wrapper", "--gradle-version", gradleVersion)
		cmd.Dir = tmp
		cmd.Env = os.Environ()
		if out, err := cmd.CombinedOutput(); err == nil {
			// copy generated files
			files := []struct{ src, dst string }{
				{filepath.Join(tmp, "gradlew"), filepath.Join(outputDir, "gradlew")},
				{filepath.Join(tmp, "gradlew.bat"), filepath.Join(outputDir, "gradlew.bat")},
				{filepath.Join(tmp, "gradle", "wrapper", "gradle-wrapper.jar"), filepath.Join(outputDir, "gradle", "wrapper", "gradle-wrapper.jar")},
				{filepath.Join(tmp, "gradle", "wrapper", "gradle-wrapper.properties"), filepath.Join(outputDir, "gradle", "wrapper", "gradle-wrapper.properties")},
			}
			for _, f := range files {
				b, err := os.ReadFile(f.src)
				if err != nil {
					return fmt.Errorf("expected generated file %s not found: %w", f.src, err)
				}
				if err := os.MkdirAll(filepath.Dir(f.dst), 0o755); err != nil {
					return err
				}
				if err := os.WriteFile(f.dst, b, 0o755); err != nil {
					return err
				}
			}
			if runtime.GOOS != "windows" {
				_ = os.Chmod(filepath.Join(outputDir, "gradlew"), 0o755)
			}
			_ = out
			return nil
		} else {
			return fmt.Errorf("gradle wrapper generation failed: %s", string(out))
		}
	}

	// Gradle not available - return clear, actionable instructions.
	guide := `Gradle not found in PATH.
Grimoire requires the Gradle CLI to generate a project wrapper automatically.

Quick install hints:
- Windows (Scoop): scoop install gradle
- Windows (Chocolatey): choco install gradle
- macOS (Homebrew): brew install gradle
- Linux (SDKMAN): curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install gradle
- Debian/Ubuntu (apt): sudo apt-get install gradle

After installing, ensure 'gradle' is on your PATH and re-run ` + "`grimoire new`" + `.
You can skip wrapper generation by passing '--wrapper=false' but builds will then require a local Gradle setup.
`
	return fmt.Errorf(guide)
}

// generateProjectConfig holds the extracted and validated configuration for GenerateProject.
type generateProjectConfig struct {
	appName      string
	packageName  string
	lang         string
	templateKind string
	minSdk       int
	targetSdk    int
	outputDir    string
	gitInit      bool
	vscodeCfg    bool
	skipWrapper  bool
}

// extractGenerateConfig extracts and validates configuration from the ProviderConfig.
func extractGenerateConfig(cfg providers.ProviderConfig) (*generateProjectConfig, error) {
	gc := &generateProjectConfig{}

	// AppName (required)
	gc.appName = common.GetStringDefault(cfg, "", "AppName", "app-name")
	if gc.appName == "" {
		return nil, fmt.Errorf("AppName is required in config")
	}

	// PackageName (required)
	gc.packageName = common.GetStringDefault(cfg, "", "PackageName", "package")
	if gc.packageName == "" {
		return nil, fmt.Errorf("PackageName is required in config")
	}

	// Lang (default: kotlin)
	gc.lang = common.GetStringDefault(cfg, "kotlin", "Lang", "lang")

	// Template (default: basic)
	gc.templateKind = common.GetStringDefault(cfg, "basic", "Template", "template")

	// MinSdk (default: 26)
	gc.minSdk = common.GetIntDefault(cfg, 26, "MinSdk", "min-sdk")

	// TargetSdk (default: 35)
	gc.targetSdk = common.GetIntDefault(cfg, 35, "TargetSdk", "target-sdk")

	// OutputDir (default: ./<appName>)
	gc.outputDir = common.GetStringDefault(cfg, filepath.Join(".", gc.appName), "OutputDir", "output-dir")

	// GitInit (default: false)
	gc.gitInit = common.GetBoolDefault(cfg, false, "Git", "git")

	// VscodeCfg (default: false)
	gc.vscodeCfg = common.GetBoolDefault(cfg, false, "Vscode", "vscode")

	// SkipWrapper: detect skip-wrapper flag — prefer explicit new `wrapper` flag (default true)
	gc.skipWrapper = !common.GetBoolDefault(cfg, true, "Wrapper", "wrapper", "NoWrapper", "no-wrapper")

	// If wrapper is explicitly "NoWrapper" or "no-wrapper", override
	if common.GetBoolDefault(cfg, false, "NoWrapper", "no-wrapper") {
		gc.skipWrapper = true
	}

	return gc, nil
}

// writeRootLevelFiles writes build.gradle, settings.gradle, gradle.properties, and .gitignore.
func writeRootLevelFiles(outputDir string, data map[string]any) error {
	files := []struct {
		template string
		path     string
	}{
		{"build_gradle_root.tmpl", "build.gradle"},
		{"settings_gradle.tmpl", "settings.gradle"},
		{"gradle_properties.tmpl", "gradle.properties"},
		{"gitignore.tmpl", ".gitignore"},
	}

	for _, f := range files {
		if s, err := renderTemplate(f.template, data); err == nil {
			if err := writeFile(filepath.Join(outputDir, f.path), s); err != nil {
				return err
			}
		}
	}
	return nil
}

// writeAppModuleFiles writes app/build.gradle and AndroidManifest.xml.
func writeAppModuleFiles(outputDir string, data map[string]any) error {
	appBuild, err := renderTemplate("build_gradle_app.tmpl", data)
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(outputDir, "app", "build.gradle"), appBuild); err != nil {
		return err
	}

	manifest, err := renderTemplate("AndroidManifest.xml.tmpl", data)
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "AndroidManifest.xml"), manifest); err != nil {
		return err
	}

	return nil
}

// writeMainActivityAndLayout writes the main activity and layout file based on language and template.
func writeMainActivityAndLayout(outputDir string, pkgPath, lang, templateKind string, data map[string]any) error {
	if lang == "kotlin" {
		switch templateKind {
		case "basic":
			src, _ := renderTemplate("MainActivity.kt.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.kt"), src); err != nil {
				return err
			}
			layout, _ := renderTemplate("activity_main.xml.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "res", "layout", "activity_main.xml"), layout); err != nil {
				return err
			}
		case "compose":
			src, _ := renderTemplate("MainActivity_compose.kt.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.kt"), src); err != nil {
				return err
			}
		default:
			src, _ := renderTemplate("MainActivity_empty.kt.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.kt"), src); err != nil {
				return err
			}
		}
	} else {
		if templateKind == "basic" {
			src, _ := renderTemplate("MainActivity.java.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.java"), src); err != nil {
				return err
			}
			layout, _ := renderTemplate("activity_main.xml.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "res", "layout", "activity_main.xml"), layout); err != nil {
				return err
			}
		} else {
			src, _ := renderTemplate("MainActivity_empty.java.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.java"), src); err != nil {
				return err
			}
		}
	}
	return nil
}

// writeResourceFiles writes strings.xml and themes.xml.
func writeResourceFiles(outputDir string, data map[string]any) error {
	files := []struct {
		template string
		path     string
	}{
		{"strings.xml.tmpl", filepath.Join("app", "src", "main", "res", "values", "strings.xml")},
		{"themes.xml.tmpl", filepath.Join("app", "src", "main", "res", "values", "themes.xml")},
	}

	for _, f := range files {
		if s, err := renderTemplate(f.template, data); err == nil {
			if err := writeFile(filepath.Join(outputDir, f.path), s); err != nil {
				return err
			}
		}
	}
	return nil
}

// writeVsCodeFiles writes VSCode settings and extensions files.
func writeVsCodeFiles(outputDir string, data map[string]any) error {
	files := []struct {
		template string
		path     string
	}{
		{"vscode_settings.json.tmpl", filepath.Join(".vscode", "settings.json")},
		{"vscode_extensions.json.tmpl", filepath.Join(".vscode", "extensions.json")},
	}

	for _, f := range files {
		if s, err := renderTemplate(f.template, data); err == nil {
			if err := writeFile(filepath.Join(outputDir, f.path), s); err != nil {
				return err
			}
		}
	}
	return nil
}

// GenerateProject creates a new Android project based on cfg.
func GenerateProject(cfg providers.ProviderConfig) error {
	// Extract and validate configuration
	gc, err := extractGenerateConfig(cfg)
	if err != nil {
		return err
	}

	// If user requested a Java project, or we will generate the Gradle wrapper,
	// ensure Java is available early to provide a clear error message.
	if strings.ToLower(gc.lang) == "java" || !gc.skipWrapper {
		if err := checkJavaAvailable(); err != nil {
			return err
		}
	}

	// Validation
	if err := validator.ValidateAppName(gc.appName); err != nil {
		return err
	}
	if err := validator.ValidatePackageName(gc.packageName); err != nil {
		return err
	}

	// Ensure output directory does not exist
	if _, err := os.Stat(gc.outputDir); err == nil {
		return fmt.Errorf("output directory already exists: %s", gc.outputDir)
	}

	// Prepare data for template rendering
	data := map[string]any{
		"AppName":      gc.appName,
		"AppNameLower": strings.ToLower(gc.appName),
		"PackageName":  gc.packageName,
		"PackagePath":  validator.PackageToPath(gc.packageName),
		"MinSdk":       gc.minSdk,
		"TargetSdk":    gc.targetSdk,
		"Lang":         gc.lang,
		"Template":     gc.templateKind,
	}

	// Write all file groups
	if err := writeRootLevelFiles(gc.outputDir, data); err != nil {
		return err
	}
	if err := writeAppModuleFiles(gc.outputDir, data); err != nil {
		return err
	}

	pkgPath := validator.PackageToPath(gc.packageName)
	if err := writeMainActivityAndLayout(gc.outputDir, pkgPath, gc.lang, gc.templateKind, data); err != nil {
		return err
	}
	if err := writeResourceFiles(gc.outputDir, data); err != nil {
		return err
	}

	if gc.vscodeCfg {
		if err := writeVsCodeFiles(gc.outputDir, data); err != nil {
			return err
		}
	}

	// Generate Gradle wrapper unless skipped
	if !gc.skipWrapper {
		if err := ensureGradleWrapper(gc.outputDir, "8.9"); err != nil {
			return fmt.Errorf("gradle wrapper setup failed: %w", err)
		}
	}

	// Initialize git repository if requested
	if gc.gitInit {
		if err := initGit(gc.outputDir); err != nil {
			// non-fatal, warn
		}
	}

	return nil
}
