package android

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"text/template"

	"github.com/backsofangels/grimoire/internal/providers"
	"github.com/backsofangels/grimoire/internal/validator"
)

func renderTemplate(name string, data any) (string, error) {
	path := filepath.ToSlash(filepath.Join("templates", name))
	b, err := templateFS.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read template %s: %w", name, err)
	}
	tmpl, err := template.New(name).Parse(string(b))
	if err != nil {
		return "", fmt.Errorf("parse template %s: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template %s: %w", name, err)
	}
	return buf.String(), nil
}

func writeFile(path string, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write file %s: %w", path, err)
	}
	return nil
}

func initGit(dir string) error {
	cmd := exec.Command("git", "init")
	cmd.Dir = dir
	if err := cmd.Run(); err != nil {
		// Non-fatal
		return fmt.Errorf("git init failed: %w", err)
	}
	return nil
}

// checkJavaAvailable runs `java -version` to ensure Java is installed and on PATH.
// Returns a user-friendly error with install hints if Java is missing.
func checkJavaAvailable() error {
	if _, err := exec.LookPath("java"); err != nil {
		guide := `Java not found in PATH.
Grimoire requires Java (JDK or JRE) to run Gradle and build Android projects.

Quick install hints:
- Windows (Scoop): scoop install temurin
- Windows (Chocolatey): choco install temurin
- macOS (Homebrew): brew install temurin
- Linux (SDKMAN): curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java
- Debian/Ubuntu (apt): sudo apt-get install default-jdk

After installing, ensure 'java' is on your PATH and re-run ` + "`grimoire new`" + `.
`
		return fmt.Errorf(guide)
	}

	cmd := exec.Command("java", "-version")
	cmd.Env = os.Environ()
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("java -version failed: %w", err)
	} else {
		_ = out
	}
	return nil
}

// ensureGradleWrapper generates or downloads a Gradle wrapper into outputDir.
// Strategy:
// 1) If `gradle` CLI is available, run `gradle wrapper --gradle-version <ver>` in a temp dir and copy results.
// 2) Otherwise download the Gradle distribution zip and assemble the wrapper jar from it.
func ensureGradleWrapper(outputDir, gradleVersion string) error {
	// Verify Java is available before invoking Gradle.
	if err := checkJavaAvailable(); err != nil {
		return err
	}
	// Use system `gradle` to generate the wrapper. If it's not available, return
	// a helpful error directing the user to install Gradle for their OS.
	if p, err := exec.LookPath("gradle"); err == nil && p != "" {
		tmp, err := os.MkdirTemp("", "gradle-wrapper-gen-*")
		if err != nil {
			return fmt.Errorf("mktemp: %w", err)
		}
		defer os.RemoveAll(tmp)

		// Create minimal Gradle build files so `gradle wrapper` can run in a
		// fresh temp directory. Gradle requires at least a settings or build
		// file to consider the directory a build root.
		settings := "rootProject.name = 'grimoire-wrapper-temp'\n"
		if err := os.WriteFile(filepath.Join(tmp, "settings.gradle"), []byte(settings), 0o644); err != nil {
			return fmt.Errorf("write temp settings.gradle: %w", err)
		}
		build := "// minimal build file generated by grimoire\n"
		if err := os.WriteFile(filepath.Join(tmp, "build.gradle"), []byte(build), 0o644); err != nil {
			return fmt.Errorf("write temp build.gradle: %w", err)
		}

		cmd := exec.Command(p, "wrapper", "--gradle-version", gradleVersion)
		cmd.Dir = tmp
		cmd.Env = os.Environ()
		if out, err := cmd.CombinedOutput(); err == nil {
			// copy generated files
			files := []struct{ src, dst string }{
				{filepath.Join(tmp, "gradlew"), filepath.Join(outputDir, "gradlew")},
				{filepath.Join(tmp, "gradlew.bat"), filepath.Join(outputDir, "gradlew.bat")},
				{filepath.Join(tmp, "gradle", "wrapper", "gradle-wrapper.jar"), filepath.Join(outputDir, "gradle", "wrapper", "gradle-wrapper.jar")},
				{filepath.Join(tmp, "gradle", "wrapper", "gradle-wrapper.properties"), filepath.Join(outputDir, "gradle", "wrapper", "gradle-wrapper.properties")},
			}
			for _, f := range files {
				b, err := os.ReadFile(f.src)
				if err != nil {
					return fmt.Errorf("expected generated file %s not found: %w", f.src, err)
				}
				if err := os.MkdirAll(filepath.Dir(f.dst), 0o755); err != nil {
					return err
				}
				if err := os.WriteFile(f.dst, b, 0o755); err != nil {
					return err
				}
			}
			if runtime.GOOS != "windows" {
				_ = os.Chmod(filepath.Join(outputDir, "gradlew"), 0o755)
			}
			_ = out
			return nil
		} else {
			return fmt.Errorf("gradle wrapper generation failed: %s", string(out))
		}
	}

	// Gradle not available - return clear, actionable instructions.
	guide := `Gradle not found in PATH.
Grimoire requires the Gradle CLI to generate a project wrapper automatically.

Quick install hints:
- Windows (Scoop): scoop install gradle
- Windows (Chocolatey): choco install gradle
- macOS (Homebrew): brew install gradle
- Linux (SDKMAN): curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install gradle
- Debian/Ubuntu (apt): sudo apt-get install gradle

After installing, ensure 'gradle' is on your PATH and re-run ` + "`grimoire new`" + `.
You can skip wrapper generation with '--no-wrapper' but builds will then require a local Gradle setup.
`
	return fmt.Errorf(guide)
}

// GenerateProject creates a new Android project based on cfg.
func GenerateProject(cfg providers.ProviderConfig) error {
	// Extract values from cfg (support both test-style CamelCase and flag-style names)
	appName, _ := cfg["AppName"].(string)
	if appName == "" {
		if s, _ := cfg["app-name"].(string); s != "" {
			appName = s
		}
	}
	if appName == "" {
		return fmt.Errorf("AppName is required in config")
	}
	packageName, _ := cfg["PackageName"].(string)
	if packageName == "" {
		if s, _ := cfg["package"].(string); s != "" {
			packageName = s
		}
	}
	if packageName == "" {
		return fmt.Errorf("PackageName is required in config")
	}
	lang, _ := cfg["Lang"].(string)
	if lang == "" {
		if s, _ := cfg["lang"].(string); s != "" {
			lang = s
		} else {
			lang = "kotlin"
		}
	}
	templateKind, _ := cfg["Template"].(string)
	if templateKind == "" {
		if s, _ := cfg["template"].(string); s != "" {
			templateKind = s
		} else {
			templateKind = "basic"
		}
	}
	minSdk, _ := cfg["MinSdk"].(int)
	if minSdk == 0 {
		if v, ok := cfg["min-sdk"].(int); ok {
			minSdk = v
		}
		if v2, ok := cfg["min-sdk"].(string); ok {
			if n, err := strconv.Atoi(v2); err == nil {
				minSdk = n
			}
		}
		if minSdk == 0 {
			minSdk = 26
		}
	}
	targetSdk, _ := cfg["TargetSdk"].(int)
	if targetSdk == 0 {
		if v, ok := cfg["target-sdk"].(int); ok {
			targetSdk = v
		}
		if v2, ok := cfg["target-sdk"].(string); ok {
			if n, err := strconv.Atoi(v2); err == nil {
				targetSdk = n
			}
		}
		if targetSdk == 0 {
			targetSdk = 35
		}
	}
	outputDir, _ := cfg["OutputDir"].(string)
	if outputDir == "" {
		if s, _ := cfg["output-dir"].(string); s != "" {
			outputDir = s
		}
		if outputDir == "" {
			outputDir = filepath.Join(".", appName)
		}
	}
	gitInit, _ := cfg["Git"].(bool)
	if !gitInit {
		if v, ok := cfg["git"].(bool); ok {
			gitInit = v
		}
	}
	vscodeCfg, _ := cfg["Vscode"].(bool)
	if !vscodeCfg {
		if v, ok := cfg["vscode"].(bool); ok {
			vscodeCfg = v
		}
	}

	// detect skip-wrapper flag
	skipWrapper := false
	if v, ok := cfg["NoWrapper"].(bool); ok && v {
		skipWrapper = true
	}
	if v, ok := cfg["no-wrapper"].(bool); ok && v {
		skipWrapper = true
	}

	// If user requested a Java project, or we will generate the Gradle wrapper,
	// ensure Java is available early to provide a clear error message.
	if strings.ToLower(lang) == "java" || !skipWrapper {
		if err := checkJavaAvailable(); err != nil {
			return err
		}
	}

	// Validation
	if err := validator.ValidateAppName(appName); err != nil {
		return err
	}
	if err := validator.ValidatePackageName(packageName); err != nil {
		return err
	}

	// Ensure output directory does not exist
	if _, err := os.Stat(outputDir); err == nil {
		return fmt.Errorf("output directory already exists: %s", outputDir)
	}

	// Create basic files
	data := map[string]any{
		"AppName":      appName,
		"AppNameLower": strings.ToLower(appName),
		"PackageName":  packageName,
		"PackagePath":  validator.PackageToPath(packageName),
		"MinSdk":       minSdk,
		"TargetSdk":    targetSdk,
		"Lang":         lang,
		"Template":     templateKind,
	}

	// write root-level templates
	if s, err := renderTemplate("build_gradle_root.tmpl", data); err == nil {
		if err := writeFile(filepath.Join(outputDir, "build.gradle"), s); err != nil {
			return err
		}
	}
	if s, err := renderTemplate("settings_gradle.tmpl", data); err == nil {
		if err := writeFile(filepath.Join(outputDir, "settings.gradle"), s); err != nil {
			return err
		}
	}
	if s, err := renderTemplate("gradle_properties.tmpl", data); err == nil {
		if err := writeFile(filepath.Join(outputDir, "gradle.properties"), s); err != nil {
			return err
		}
	}
	if s, err := renderTemplate("gitignore.tmpl", data); err == nil {
		if err := writeFile(filepath.Join(outputDir, ".gitignore"), s); err != nil {
			return err
		}
	}

	// app module
	appBuild, err := renderTemplate("build_gradle_app.tmpl", data)
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(outputDir, "app", "build.gradle"), appBuild); err != nil {
		return err
	}

	// AndroidManifest
	manifest, err := renderTemplate("AndroidManifest.xml.tmpl", data)
	if err != nil {
		return err
	}
	if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "AndroidManifest.xml"), manifest); err != nil {
		return err
	}

	// source directory and main activity
	pkgPath := validator.PackageToPath(packageName)
	if lang == "kotlin" {
		switch templateKind {
		case "basic":
			src, _ := renderTemplate("MainActivity.kt.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.kt"), src); err != nil {
				return err
			}
			layout, _ := renderTemplate("activity_main.xml.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "res", "layout", "activity_main.xml"), layout); err != nil {
				return err
			}
		case "compose":
			// Compose activity: generate a Compose-based MainActivity
			src, _ := renderTemplate("MainActivity_compose.kt.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.kt"), src); err != nil {
				return err
			}
		default:
			src, _ := renderTemplate("MainActivity_empty.kt.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.kt"), src); err != nil {
				return err
			}
		}
	} else {
		if templateKind == "basic" {
			src, _ := renderTemplate("MainActivity.java.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.java"), src); err != nil {
				return err
			}
			layout, _ := renderTemplate("activity_main.xml.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "res", "layout", "activity_main.xml"), layout); err != nil {
				return err
			}
		} else {
			src, _ := renderTemplate("MainActivity_empty.java.tmpl", data)
			if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "java", pkgPath, "MainActivity.java"), src); err != nil {
				return err
			}
		}
	}

	// values
	if s, err := renderTemplate("strings.xml.tmpl", data); err == nil {
		if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "res", "values", "strings.xml"), s); err != nil {
			return err
		}
	}
	if s, err := renderTemplate("themes.xml.tmpl", data); err == nil {
		if err := writeFile(filepath.Join(outputDir, "app", "src", "main", "res", "values", "themes.xml"), s); err != nil {
			return err
		}
	}

	// vscode
	if vscodeCfg {
		if s, err := renderTemplate("vscode_settings.json.tmpl", data); err == nil {
			if err := writeFile(filepath.Join(outputDir, ".vscode", "settings.json"), s); err != nil {
				return err
			}
		}
		if s, err := renderTemplate("vscode_extensions.json.tmpl", data); err == nil {
			if err := writeFile(filepath.Join(outputDir, ".vscode", "extensions.json"), s); err != nil {
				return err
			}
		}
	}

	// Gradle wrapper: generate or download unless skipped
	if !skipWrapper {
		if err := ensureGradleWrapper(outputDir, "8.9"); err != nil {
			// non-fatal for generation; surface error
			return fmt.Errorf("gradle wrapper setup failed: %w", err)
		}
	}

	if gitInit {
		if err := initGit(outputDir); err != nil {
			// non-fatal, warn
		}
	}

	return nil
}
