blank_issues_enabled: false
contact_links:
  - name: 💬 General discussions
    url: https://github.com/backsofangels/grimoire/discussions
    about: For questions and ideas, use Discussions instead of Issues